[2025-01-18 00:22:49] INFO [image_service] [image_service.py:29] Starting image processing for job 0066f272-6334-48f2-bb5c-92527e84e2ea
[2025-01-18 00:22:58] ERROR [image_service] [image_service.py:127] Error in job 0066f272-6334-48f2-bb5c-92527e84e2ea: Error processing image: (psycopg2.errors.UndefinedColumn) column "storage_path" of relation "images" does not exist
LINE 1: ... INTO images (id, filename, user_id, uploaded_at, storage_pa...
                                                             ^

[SQL: INSERT INTO images (id, filename, user_id, uploaded_at, storage_path) VALUES (%(id)s::UUID, %(filename)s, %(user_id)s, %(uploaded_at)s, %(storage_path)s)]
[parameters: {'id': UUID('1b663fe3-e62a-4397-a180-28984fea0225'), 'filename': 'Screenshot 2025-01-16 at 11.18.19\u202fAM.png', 'user_id': 'user_2rUfnyh68uZAwot0qzRLALTdVOc', 'uploaded_at': datetime.datetime(2025, 1, 18, 5, 22, 58, 45241), 'storage_path': '/Users/arekhalpern/Code/soloprojects/2025/elucide/backend/uploads/6b12447c-0c76-4d69-ba09-a57bcde33960.png'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "storage_path" of relation "images" does not exist
LINE 1: ... INTO images (id, filename, user_id, uploaded_at, storage_pa...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/arekhalpern/Code/soloprojects/2025/elucide/backend/app/services/image_service.py", line 91, in process_image
    stored_image = storage.store_image(image_path, filename, user_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/Code/soloprojects/2025/elucide/backend/app/db/repositories/storage.py", line 89, in store_image
    self.db.commit()
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
    with util.safe_reraise():
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1227, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/arekhalpern/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "storage_path" of relation "images" does not exist
LINE 1: ... INTO images (id, filename, user_id, uploaded_at, storage_pa...
                                                             ^

[SQL: INSERT INTO images (id, filename, user_id, uploaded_at, storage_path) VALUES (%(id)s::UUID, %(filename)s, %(user_id)s, %(uploaded_at)s, %(storage_path)s)]
[parameters: {'id': UUID('1b663fe3-e62a-4397-a180-28984fea0225'), 'filename': 'Screenshot 2025-01-16 at 11.18.19\u202fAM.png', 'user_id': 'user_2rUfnyh68uZAwot0qzRLALTdVOc', 'uploaded_at': datetime.datetime(2025, 1, 18, 5, 22, 58, 45241), 'storage_path': '/Users/arekhalpern/Code/soloprojects/2025/elucide/backend/uploads/6b12447c-0c76-4d69-ba09-a57bcde33960.png'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-01-18 00:25:49] INFO [image_service] [image_service.py:29] Starting image processing for job dbfff246-1907-4e0f-84f2-ee1f80bf946e
[2025-01-18 00:25:54] INFO [image_service] [image_service.py:92] Stored image with ID: 442e1292-fde9-4b65-8501-ef9223ff1e1c
[2025-01-18 00:25:54] INFO [image_service] [image_service.py:119] Returning result with processing time: 18005.27
[2025-01-18 00:26:29] INFO [image_service] [image_service.py:29] Starting image processing for job e926a1a7-f50f-4168-9633-c67c985a5dd7
[2025-01-18 00:26:37] INFO [image_service] [image_service.py:92] Stored image with ID: 11d449e4-140a-41a0-9b06-53c2861c0ab6
[2025-01-18 00:26:37] INFO [image_service] [image_service.py:119] Returning result with processing time: 18008.45
[2025-01-18 00:31:54] INFO [image_service] [image_service.py:29] Starting image processing for job 77caaf89-53bd-4aab-81f7-f5b6baa91401
[2025-01-18 00:32:00] INFO [image_service] [image_service.py:92] Stored image with ID: 155eb9e3-d672-43bf-b236-d46fd2253f87
[2025-01-18 00:32:00] INFO [image_service] [image_service.py:119] Returning result with processing time: 18005.84
[2025-01-18 00:34:46] INFO [image_service] [image_service.py:29] Starting image processing for job 1e3f2fde-ee64-4993-8764-2f32c75f85e4
[2025-01-18 00:34:54] INFO [image_service] [image_service.py:92] Stored image with ID: 166383e8-364a-4601-b440-e3b73bce761c
[2025-01-18 00:34:54] INFO [image_service] [image_service.py:119] Returning result with processing time: 18007.81
[2025-01-18 00:37:00] INFO [image_service] [image_service.py:29] Starting image processing for job df22602b-4a66-4380-b5b1-718bfcd43204
[2025-01-18 00:37:04] INFO [image_service] [image_service.py:92] Stored image with ID: 1cbcbd73-d732-4b0f-8911-f7ec8ee03da1
[2025-01-18 00:37:04] INFO [image_service] [image_service.py:119] Returning result with processing time: 18004.49
[2025-01-18 00:38:26] INFO [image_service] [image_service.py:29] Starting image processing for job ed743aae-c325-4803-8ed9-37050b26bf98
[2025-01-18 00:38:31] INFO [image_service] [image_service.py:92] Stored image with ID: 8da71d0c-39e3-47f5-8ff4-5c7c71e8d33f
[2025-01-18 00:38:31] INFO [image_service] [image_service.py:119] Returning result with processing time: 18005.08
[2025-01-18 00:43:18] INFO [image_service] [image_service.py:29] Starting image processing for job 0b3a30bc-a789-443b-9b8a-7e281f9666c3
[2025-01-18 00:43:22] INFO [image_service] [image_service.py:92] Stored image with ID: 433a87f9-7ca4-4316-96e7-3fe305d5f29d
[2025-01-18 00:43:22] INFO [image_service] [image_service.py:119] Returning result with processing time: 18003.87
[2025-01-18 00:45:17] INFO [image_service] [image_service.py:29] Starting image processing for job 59000df4-71a2-4e8d-8e03-f84a784da855
[2025-01-18 00:45:24] INFO [image_service] [image_service.py:92] Stored image with ID: bbb44c66-fb4e-4b37-8860-0e71eb38e982
[2025-01-18 00:45:24] INFO [image_service] [image_service.py:119] Returning result with processing time: 18006.96
[2025-01-18 00:47:10] INFO [image_service] [image_service.py:29] Starting image processing for job c9f70e93-73d2-4d69-a4ab-e6178307d11d
[2025-01-18 00:47:16] INFO [image_service] [image_service.py:92] Stored image with ID: c9b3f289-89ef-4306-9ecf-d695e2d41e23
[2025-01-18 00:47:16] INFO [image_service] [image_service.py:119] Returning result with processing time: 6.0
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 0b1891ba-b4da-42e3-9ea7-2e26d58e7ff1
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 864ed023-7782-48c0-9bf1-f1e8fecfed01
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 4f3ae89e-cbae-4b87-abde-f18b97ae9981
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 0ba62eb8-855d-408a-b4ea-8fdc0df38aac
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 6a7ca82e-bb48-466a-a0da-09dc557adbff
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 6cde5841-0113-427b-89ed-b5c276749a43
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 90c9aaa4-3703-4a15-80d7-6b45e8831f0c
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job e6725dbd-377e-4802-b75a-2495d31d28d1
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job 7ba9aff9-3828-471c-a727-86505ee1879d
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job bee63680-8839-4990-afa0-e8e45045d525
[2025-01-19 14:34:51] INFO [image_service] [image_service.py:29] Starting image processing for job caf8027a-6397-488d-901b-4653dfaa5a61
[2025-01-19 14:34:52] INFO [image_service] [image_service.py:29] Starting image processing for job ac567a68-2ada-470f-a871-3afc6515e642
[2025-01-19 14:34:55] INFO [image_service] [image_service.py:92] Stored image with ID: 4174acf0-ea10-436d-930e-c8d425381f4f
[2025-01-19 14:34:55] INFO [image_service] [image_service.py:119] Returning result with processing time: 3.83
[2025-01-19 14:34:55] INFO [image_service] [image_service.py:29] Starting image processing for job 9b98035b-be0a-4ba3-bff7-8ce1c656fd59
[2025-01-19 14:34:55] INFO [image_service] [image_service.py:92] Stored image with ID: dc40f1e1-0300-41a4-b46c-e2248bec518d
[2025-01-19 14:34:55] INFO [image_service] [image_service.py:119] Returning result with processing time: 4.05
[2025-01-19 14:34:56] INFO [image_service] [image_service.py:92] Stored image with ID: 09581b35-9caf-49fe-aaa6-29ac39a6dd3c
[2025-01-19 14:34:56] INFO [image_service] [image_service.py:119] Returning result with processing time: 4.5
[2025-01-19 14:34:56] INFO [image_service] [image_service.py:92] Stored image with ID: 577b4a27-eb12-4e87-8e06-ee8b0235c36f
[2025-01-19 14:34:56] INFO [image_service] [image_service.py:119] Returning result with processing time: 4.97
[2025-01-19 14:34:56] INFO [image_service] [image_service.py:92] Stored image with ID: 56344ce5-4abd-47a0-b5dd-151793d42993
[2025-01-19 14:34:56] INFO [image_service] [image_service.py:119] Returning result with processing time: 4.97
[2025-01-19 14:34:57] INFO [image_service] [image_service.py:92] Stored image with ID: 98ea626c-60b5-4cb4-8300-4d424f7d783b
[2025-01-19 14:34:57] INFO [image_service] [image_service.py:119] Returning result with processing time: 5.63
[2025-01-19 14:34:57] INFO [image_service] [image_service.py:92] Stored image with ID: d0208de3-b1b4-4c3c-afe9-44b7fbaa8898
[2025-01-19 14:34:57] INFO [image_service] [image_service.py:119] Returning result with processing time: 5.82
[2025-01-19 14:34:57] INFO [image_service] [image_service.py:92] Stored image with ID: 721d63de-ad09-460c-a3d9-3e7ac6d96c98
[2025-01-19 14:34:57] INFO [image_service] [image_service.py:119] Returning result with processing time: 5.88
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:92] Stored image with ID: 2c3615fd-334c-43ff-aefe-3f27df64e45c
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:119] Returning result with processing time: 6.33
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:92] Stored image with ID: 384da594-5923-4df8-8330-d20633529070
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:119] Returning result with processing time: 6.48
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:92] Stored image with ID: e8bc4f02-01f4-4531-b381-113eacf49f33
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:119] Returning result with processing time: 2.76
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:92] Stored image with ID: 7f1be9d3-fe91-4885-afea-ac741063bdc6
[2025-01-19 14:34:58] INFO [image_service] [image_service.py:119] Returning result with processing time: 7.28
[2025-01-19 14:35:02] INFO [image_service] [image_service.py:92] Stored image with ID: c3babf08-14f7-41ac-8e2d-9e9af6fcc7b4
[2025-01-19 14:35:02] INFO [image_service] [image_service.py:119] Returning result with processing time: 10.6
[2025-01-23 15:18:37] INFO [image_service] [image_service.py:29] Starting image processing for job 76aaba37-64b1-422f-836b-474559330347
[2025-01-23 15:18:42] INFO [image_service] [image_service.py:92] Stored image with ID: 60c0f847-ae40-4cee-811f-335b545210c6
[2025-01-23 15:18:42] INFO [image_service] [image_service.py:119] Returning result with processing time: 18004.5
[2025-01-23 15:20:33] INFO [image_service] [image_service.py:29] Starting image processing for job c0e5a81b-1d21-43f4-bec7-bc0ac413e79a
[2025-01-23 15:20:42] INFO [image_service] [image_service.py:92] Stored image with ID: 5386a43a-e4b5-4a63-af80-a699367fc1a5
[2025-01-23 15:20:42] INFO [image_service] [image_service.py:119] Returning result with processing time: 18008.83
[2025-01-23 15:22:02] INFO [image_service] [image_service.py:29] Starting image processing for job 2b86fca9-710e-4fc9-bad5-e5b47a5c3812
[2025-01-23 15:22:11] INFO [image_service] [image_service.py:92] Stored image with ID: 23362bad-1340-4c7b-87a9-2c0b242d756b
[2025-01-23 15:22:11] INFO [image_service] [image_service.py:119] Returning result with processing time: 18009.63
[2025-01-23 15:23:32] INFO [image_service] [image_service.py:29] Starting image processing for job 65bcb9f4-19a3-4b80-81ac-bc5179527bb9
[2025-01-23 15:23:40] INFO [image_service] [image_service.py:92] Stored image with ID: eb7cc1b7-6281-48a3-b8e8-76fcf78e1944
[2025-01-23 15:23:40] INFO [image_service] [image_service.py:119] Returning result with processing time: 8.76
